name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - requests
  - opencv-python
  - streamlit-webrtc
  - aiortc==1.0.0
  - dlib
  - cmake
  - fpdf
  - tensorflow
  - prometheus_client
  - databases[sqlite]
  - sqlalchemy
  - transformers
  - reportlab
  - python-multipart
  - plotly
  - streamlit
  - fastapi
  - uvicorn
  - face-recognition
  - protobuf==3.20.*
  - pip
  - pip:
      - ollama
